# Generated by Django 6.0.2 on 2026-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='main_image',
        ),
        migrations.AddField(
            model_name='place',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='booking_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('nature', 'Nature'), ('pilgrimage', 'Pilgrimage'), ('heritage', 'Heritage'), ('hidden', 'Hidden')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='essential_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='how_to_reach',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='nearby_facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
