# Generated by Django 6.0.2 on 2026-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_remove_place_description_remove_place_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='entry_booking',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='safety_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='trekking_info',
            field=models.TextField(blank=True),
        ),
    ]
